### ISSUE TITLE
How do Nest slove that two modules have the same name?

### ISSUE THREAD

**Issue by TimeEternal** [ZhouYanzhao/Nest#3]
In the README, i think we should use modules.xxx to call the xxx function, so that this shou cause a problem when two modules have the same name.

**Comment by ZhouYanzhao** [comment]
@TimeEternal 
You could register them under different namespaces `nest module install code_folder_a namespace_a; nest module install code_folder_b namespace_b` and access them as follow:
```python
    >>> from nest import modules
    >>> modules['namesapce_a.func'](arg)
    >>> modules['namesapce_b.func'](arg)
    >>> modules['*a.func'](arg) # Wildcard
    >>> modules['*b.func'](arg) # Wildcard
    >>> modules['func'](arg) # In this case, Nest will warn you that multiple modules match your query.
```

**Comment by TimeEternal** [comment]
Thanks for your reply
